name: Continuous Patch 

env:
  CURRENT_VERSION: ${{ vars.LATEST_PATCHED_VERSION }}
  SCRAPED_VERSION: ""
  YUKIHANA_FIDDLER_NAME: "fiddler.dll"

on:
  push:
      branches:
        - main  
  workflow_dispatch:

jobs:
  compare-versions:
    runs-on: windows-latest
    # needs: scrape-fe-version-and-set-env

    outputs:
      should_continue: ${{ steps.should_continue.outputs.should_continue }}
    steps:
    
    - name: Check Should Continue
      id: should_continue
      run: |
        $scrapedVersion = "5.17.0"
        $compareVersion = "5.16.0"
   
        Write-Host "SCRAPED_VERSION: $scrapedVersion"
        Write-Host "Compare Version: $compareVersion"

        if (-not [string]::IsNullOrEmpty($scrapedVersion)) {
            if ([version]$scrapedVersion -ge [version]$compareVersion) {
                echo "should_continue=true" >> $GITHUB_OUTPUT
            } else {
                echo "should_continue=false" >> $GITHUB_OUTPUT
            }
        } else {
            echo "should_continue=false" >> $GITHUB_OUTPUT
        }
        
      shell: pwsh

  ran-holy-tnx:
    runs-on: windows-latest
    needs: compare-versions
    if: ${{ needs.compare-versions.outputs.should_continue }} == 'true'

    steps:
    
      - name: Tnx
        run: echo "Tnx god"
