# This is a basic workflow to help you get started with Actions

name: Download & Compere FE

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      current-version:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Steps represent a sequence of tasks that will be executed as part of the job
  download-fe:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Download Fiddler Everywhere with original filename
        run: |
          # Use curl to download the file with the name provided by the server
          curl -L -OJ https://www.telerik.com/download/fiddler/fiddler-everywhere-windows

      - name: List downloaded file
        run: dir  # 'dir' is the command to list files in Windows


