# This is a basic workflow to help you get started with Actions

name: Download & Compere FE

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      current-version:
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Steps represent a sequence of tasks that will be executed as part of the job
  download-fe:
    # The type of runner that the job will run on
    runs-on: windows-latest

    steps:
      - name: Get FE Filename
        run: |
          $url = "https://www.telerik.com/download/fiddler/fiddler-everywhere-windows"
          $response = Invoke-WebRequest -Uri $url
          $html = $response.Content

          # Look for the download link in the HTML
          $downloadLink = $null
          $html -match '<a[^>]*href="([^"]*Fiddler Everywhere[^"]*\.exe)"' | Out-Null
          if ($matches) {
              $downloadLink = $matches[1]
              $filename = [System.IO.Path]::GetFileName($downloadLink)
          } else {
              $filename = "Filename not found in HTML."
          }

          Write-Host "Download filename: $filename"
