# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Fe Version (Current) Scraper

on:
  workflow_dispatch:
  workflow_call:

jobs:
  scrape-fe-version:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.9.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: node .

    - name: Upload latest version file
      uses: actions/upload-artifact@v4
      with:
        name: scraped-version-number
        path: utils/fe-version-scraper/latest_version.txt
