name: Continuous Patch 

on:
  push:
      branches:
        - main  
  workflow_dispatch:

jobs:
  scrape_fe_version:
    runs-on: windows-latest
    
    outputs:
      ee: ${{ steps.wd.outputs.sdc }}
      
    steps:
    - name: RE
      id: wd
      run: echo "sdc=wdqwd" >> $GITHUB_OUTPUT

  compare-versions:
    runs-on: windows-latest
    needs: scrape_fe_version

    steps:
    - name: Print
      env:
        TEST: ${{ needs.scrape_fe_version.outputs.ee }}
      run: 
        echo "$TEST"
