name: Learn 

env:
  CURRENT_VERSION: ${{ vars.LATEST_PATCHED_VERSION }}
  
on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      step1: ${{ steps.step1.outputs.step1 }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "step1=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
      THENENV: ${{needs.job1.outputs.step1}}
    steps:
      - env:
          OUTPUT1: ${{ env.THENENV }}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
